### ISSUE TITLE
NameError: name 'y' is not defined

### ISSUE THREAD

**Issue by kakakaya** [Girls-anime-lover/Aikatsu-QR-Slack-Post-Program#24]
`retry.lower() == 'y'` とかの間違い？

https://github.com/Girls-anime-lover/Aikatsu-QR-Slack-Post-Program/blob/f49af70b45b848cdd7f486aaf6f830f812dc8579/read.py#L93-L96

**Comment by Ricotan-naboon** [comment]
あれ自動的にクローズしてたっぽい
修正しました....
