### ISSUE TITLE
Found typo: `domein`

### ISSUE THREAD

**Issue by kakakaya** [Girls-anime-lover/Aikatsu-QR-Slack-Post-Program#25]
https://github.com/Girls-anime-lover/Aikatsu-QR-Slack-Post-Program/blob/f49af70b45b848cdd7f486aaf6f830f812dc8579/read.py#L75-L78

もしかして： **domain**

> domainの意味・使い方・読み方 | Weblio英和辞書
https://ejje.weblio.jp/content/domain

**Comment by Ricotan-naboon** [comment]
脳死状態でコードを書いてはいけない！！！()
