### ISSUE TITLE
読み取り対応できるQRについて

### ISSUE THREAD

**Issue by sean2048** [Girls-anime-lover/Aikatsu-QR-Slack-Post-Program#30]
READMEのそもそも対応できない、
のカードがほんとに読み取れないか、気になったので、とりあえず1種類だけ検証。

やった事
1. プリパラのQRをwebから拾ってくる
2. オンラインのQRスキャンサービス([URL](http://qrcode.red/))でスキャン
    文字化けした文字列が得られる
3. 既存スキャンサービスまたはアプリでは解読できないので、QRを人力で解読

分かった事
1. プリパラのQRは、形式情報、型番情報、各種位置合わせ等パターン以外、データ部分の白黒が逆なようなので反転後(誤り訂正コードも反転必要かは未確認)、通常通り解読する必要がある。
2. 誤り訂正レベルはH
3. バージョン(大きさ)は49
4. データモードはECIモード+8ビットモード
5. 8ビットモードで記載されている文字数は174?(たぶんQRによって変わる)
6. 100bit以上読み取ってみたが生文字ではなさそう
7. 格納データは数値データまたは、暗号化されている文字

以上の事が分かった。
この事から、プリパラのQRコードに対応することは不可能と考えられる。

今後は、プリチャンのQRコードも暗号化等されている可能性が高いと考えられるが、念のため検証してみたいと考えている。

使用したQRコード、読み取った情報等は、年越しまでにSlack or このissues上で問合せがあれば、何らかの方法でお渡ししたいと考えています。

最後に一言
### QRコードは人力解読するもんじゃねぇ  つかれた

**Comment by Ricotan-naboon** [comment]
暗号化ってよりも独自規格の可能性を疑っているのよね
パラは
チャンならテスト用QRあるからSlackで渡します...

**Comment by sean2048** [comment]
slackの読み取った
バージョン(大きさ) 25
誤り訂正:Q level
モード:構造的連続
