### ISSUE TITLE
SearchImage function and QRreade function are defined and never used.

### ISSUE THREAD

**Issue by Yanorei32** [Girls-anime-lover/Aikatsu-QR-Slack-Post-Program#32]
Here:
https://github.com/Girls-anime-lover/Aikatsu-QR-Slack-Post-Program/blob/WithOut-Slack/read.py#L23-L37

**Comment by Ricotan-naboon** [comment]
I fix your Point out.
Thanks!

**Comment by Yanorei32** [comment]
This repository is not updated.
Did you commit and push ?

**Comment by Ricotan-naboon** [comment]
**I DID IT!!!**

**Comment by Yanorei32** [comment]
LGTM.

**Comment by Ricotan-naboon** [comment]
![Dkt3fnqUcAAVaUN jpg large](https://user-images.githubusercontent.com/51312671/72872141-f5834700-3d2f-11ea-9404-66a40b48af40.jpeg)
